### ISSUE TITLE
Suggested pronoun checks

### ISSUE THREAD

**Issue by iHiD** [exercism/discord-bot-py#9]
https://github.com/exercism/discord-bot-py/blob/9b3de65c9f958c2d9e429dad63b604a3bc4dd0a6/conf.py#L53

Someone better with regexp than me can work this but basically the set on the left followed by an optional comma, followed by the set on the right. Something like this
```[hello hey hi yo sup morning afternoon evening]\s+,?\s?[guys boys lads dudes]```

**Comment by glennj** [comment]
add: "you guys"
